### PR TITLE
re-worked Windows part

### PR DESCRIPTION
**Pull request by FObersteiner**
I've updated the Windows part, to try the `tzutil /g` command first and then registry key read second if the first doesn't work. Also the mappings between IANA and Windows time zone names are now in a separate file (the Python script to generate the mappings is included in /util). The mappings are exported, in case somebody just needs to resolve a Windows time zone name to IANA or vice versa, this might be helpful. Check out the changes and if that is all fine with you.

### CODE REVIEW

**Review by timohuovinen — APPROVED** [review]
Thank you for the changes!
I dislike having a python dependency, I think I'll rewrite it into go.

**Comment by FObersteiner** [comment]
Great, thanks for integrating! About the Python script, Python's my "everyday language", so I didn't give it much of a thought (it's only using the Python 3 standard lib). If you feel like rewriting it in `go`, go for it :)

**Comment by timohuovinen** [comment]
Rewrote the python script into golang, what a journey that was! FTP is such an ancient pain in the butt haha.

**Comment by FObersteiner** [comment]
that really looks like a learning experience (I missed) ^^

**Pull request merged**
